### ISSUE TITLE
The Server not Working for me! 

### ISSUE THREAD

**Issue by jfflfreitas** [maxgfr/visual-recognition-server#1]
The Command "npm install && bower install && gulp bower" give me a follow error message: "'bower' is not recognized as an internal command
or external, an operational program or a batch file."

Im using windows

Im trying use the server and tha app.
The app works, but now, i want to use my own server, can you help me with this?

**Comment by maxgfr** [comment]
Try to install globally bower with this command : 
```sh
npm install -g bower
```
You may install gulp too : 
```sh
npm install -g gulp-cli
```
